[tool.poetry]
name = "custom-game-area"
version = "0.1.0"
description = ""
authors = ["reconman <reconman@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"
numpy = "^2.5"
pillow = "^12.3"
pygithub = "^2.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
