name: deploy-py-lambda
on:
  push:
    branches:
      - amazon-lambda

env:
  REGION: eu-central-1
  REGISTRY: 231037907337.dkr.ecr.eu-central-1.amazonaws.com
  IMAGE_NAME: fga-custom-game-area
  FUNCTION_NAME: custom-game-area-docker

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Deploy code to Lambda
      shell: bash
      run: |
        docker buildx build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest --push .
        aws lambda update-function-code --function-name ${{ env.FUNCTION_NAME }} --image-uri ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
