name: Serverless deployment

on:
  push:
    branches:
      - serverless

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/lambda/python:3.9
    steps:
    - run: yum install git -y
    - uses: actions/checkout@v3
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: serverless deploy
      run: |
        npm i -g serverless@3.x
        npm ci
        serverless deploy
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
