name: deploy-py-lambda
on:
  push:
    branches:
      - amazon-lambda
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Deploy code to Lambda
      uses: duoi/py-lambda-action@1.0.9
      with:
        lambda_layer_arn: 'arn:aws:lambda:eu-central-1:231037907337:layer:Dependencies'
        lambda_function_name: 'custom-game-area'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'
        # PIP_NO_BINARY: cryptography
