name: Serverless deployment

on:
  push:
    branches:
      - serverless

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/_serverless.yml
    with:
      deploy: true
    secrets:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
