name: deploy-py-lambda
on:
  push:
    branches:
      - amazon-lambda
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Deploy code to Lambda
      shell: bash
      run: |
        pip install aws
        aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 231037907337.dkr.ecr.eu-central-1.amazonaws.com
        docker buildx build -t 231037907337.dkr.ecr.eu-central-1.amazonaws.com/fga-custom-game-area:latest --push .
        aws lambda update-function-code --region eu-central-1 --function-name my-function --image-uri 231037907337.dkr.ecr.eu-central-1.amazonaws.com/fga-custom-game-area:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'
